apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voting-app-persistentvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path

  