apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voting-app-persistentvolumeclaim
  namespace: Voting-application
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path

  