apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: voting-app
spec:
  type: ClusterIP
  ports:
    - name: postgres-svc-port
      port: 5432
      targetPort: 5432
  selector:
    app: voting-app

  
    