apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    app: voting-app
spec:
  type: NodePort
  ports:
    - name: result-svc-port
      port: 80
      targetPort: 80
      nodePort: 31010
      protocol: TCP
  selector:
    app: voting-app


