apiVersion: v1
kind: Service
metadata:
  name: result-lb-service
  labels:
    app: result-app
spec:
  ports:
  - port: 5001
    targetPort: 80
    protocol: TCP
    name: resultapp-service
  type: LoadBalancer
  selector:
    app: result-app